# Generated by Django 4.1.13 on 2024-09-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('price', models.FloatField(null=True)),
                ('promo', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(null=True)),
                ('image', models.CharField(max_length=255, null=True)),
                ('stock', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('domain', models.CharField(blank=True, max_length=50, null=True)),
                ('producer', models.CharField(blank=True, max_length=50, null=True)),
                ('millesime', models.IntegerField(blank=True, null=True)),
                ('grape_variety', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('appellation', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
