# Generated by Django 3.1.12 on 2024-09-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_anonymous_user',
            field=models.BooleanField(default=False),
        ),
    ]
